=== antonbl32/FreeIt/computers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="PriceDecimal">
    <xs:restriction base="xs:double">
      <xs:minInclusive value="50"/>
      <xs:maxInclusive value="1000"/>
      <xs:pattern value="\d+\.\d+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="computers" type="computersType">
    <xs:complexType id=""
  </xs:element>
  <xs:complexType name="hddType">
    <xs:sequence>
      <xs:element name="brand">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Hitachi"/>
            <xs:enumeration value="Toshiba"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="critical"/>
      <xs:element name="price">
        <xs:simpleType>
          <xs:restriction base="PriceDecimal">
            <xs:enumeration value="55.0"/>
            <xs:enumeration value="61.0"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="motherBoardType">
    <xs:sequence>
      <xs:element name="brand">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Foxconn"/>
            <xs:enumeration value="Malta"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="critical"/>
      <xs:element name="price">
        <xs:simpleType>
          <xs:restriction base="PriceDecimal">
            <xs:enumeration value="95.5"/>
            <xs:enumeration value="91.5"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="VCardType">
    <xs:sequence>
      <xs:element name="brand">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Nvideo"/>
            <xs:enumeration value="ATI"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="critical"/>
      <xs:element name="price">
        <xs:simpleType>
          <xs:restriction base="PriceDecimal">
            <xs:enumeration value="255.5"/>
            <xs:enumeration value="215.9"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ListOfComputersType">
    <xs:sequence>
      <xs:element type="hddType" name="hdd"/>
      <xs:element name="id">
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="motherBoardType" name="motherBoard"/>
      <xs:element name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="First"/>
            <xs:enumeration value="Second"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="price">
        <xs:simpleType>
          <xs:restriction base="PriceDecimal">
            <xs:enumeration value="406.0"/>
            <xs:enumeration value="368.4"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="VCardType" name="VCard"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="computersType">
    <xs:sequence>
      <xs:element type="xs:string" name="id"/>
      <xs:element type="ListOfComputersType" name="ListOfComputers" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="shopName" default="Default value"/>
  </xs:complexType>
</xs:schema>

=== antonbl32/FreeIt/computers.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<computers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" shopName="MaxComp" xsi:noNamespaceSchemaLocation="computers.xsd">
    <id>1</id>
    <ListOfComputers>
        <hdd>
            <brand>Hitachi</brand>
            <critical>false</critical>
            <price>55.0</price>
        </hdd>
        <id>1</id>
        <motherBoard>
            <brand>Foxconn</brand>
            <critical>true</critical>
            <price>95.5</price>
        </motherBoard>
        <name>First</name>
        <price>406.0</price>
        <VCard>
            <brand>Nvideo</brand>
            <critical>true</critical>
            <price>255.5</price>
        </VCard>
    </ListOfComputers>
    <ListOfComputers>
        <hdd>
            <brand>Toshiba</brand>
            <critical>false</critical>
            <price>61.0</price>
        </hdd>
        <id>2</id>
        <motherBoard>
            <brand>Malta</brand>
            <critical>true</critical>
            <price>91.5</price>
        </motherBoard>
        <name>Second</name>
        <price>368.4</price>
        <VCard>
            <brand>ATI</brand>
            <critical>true</critical>
            <price>215.9</price>
        </VCard>
    </ListOfComputers>
</computers>
